# Generated by Django 4.2.5 on 2023-10-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banklist_api", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="full_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="banklist_api.bank",
            ),
        ),
    ]
