# Generated by Django 4.2.5 on 2023-10-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
