# Generated by Django 4.2.5 on 2023-10-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0003_alter_payslip_date"),
        ("employees", "0005_alter_employee_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr_dashboard.department",
            ),
        ),
    ]
