# Generated by Django 4.2.5 on 2023-10-04 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="standard_salary",
        ),
        migrations.RemoveField(
            model_name="department",
            name="standard_salary_currency",
        ),
    ]
