# Generated by Django 4.2.5 on 2023-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="type",
            field=models.CharField(
                choices=[
                    ("TAX", "Tax"),
                    ("DEBT", "Shortfall"),
                    ("ABSENCE", "Absence Penalty"),
                    ("SALARY_ADVANCE", "Salary Advance"),
                    ("OTHERS", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
