# Generated by Django 4.2.5 on 2023-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0002_alter_deduction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
