# Generated by Django 4.2.5 on 2023-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0002_remove_employee_bank_name_remove_employee_full_name_and_more",
        ),
        ("hr_dashboard", "0002_remove_department_standard_salary_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="payslip",
            name="month",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("employee", "month", "year")},
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="month_year",
        ),
    ]
