# Generated by Django 4.2.5 on 2023-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0003_alter_payslip_unique_together_payslip_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
