# Generated by Django 4.2.5 on 2023-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0005_department_standard_wages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduction",
            name="amount_currency",
        ),
        migrations.RemoveField(
            model_name="department",
            name="standard_wages_currency",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="bonuses_currency",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="earnings_currency",
        ),
        migrations.AlterField(
            model_name="deduction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="department",
            name="standard_wages",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="bonuses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
