# Generated by Django 4.2.5 on 2023-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0005_remove_deduction_payslip_deduction_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Unpaid", "Unpaid"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
