# Generated by Django 4.2.5 on 2023-10-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0007_payslip_basic_salary_at_time_of_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="row",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="hr_dashboard.department",
                    ),
                ),
            ],
        ),
    ]
