# Generated by Django 4.2.5 on 2023-10-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_employee_home_address_employee_is_salary_set"),
        ("hr_dashboard", "0008_department_row_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="status",
            field=models.CharField(
                choices=[("Unused", "Unused"), ("Issued", "Issued")],
                default="Unused",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="used_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employee",
            ),
        ),
    ]
