# Generated by Django 4.2.5 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0009_verificationcode_status_verificationcode_used_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="basic_pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="basic_salary_at_time_of_generation",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
