# Generated by Django 4.2.5 on 2023-10-17 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0010_department_basic_pay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="row",
            field=models.IntegerField(),
        ),
    ]
