# Generated by Django 4.2.5 on 2023-10-17 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hr_dashboard", "0011_deduction_created_at_alter_department_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="date",
        ),
        migrations.AddField(
            model_name="payslip",
            name="generated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="deduction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
